site_name: eve-analytics

nav:
  - Home: index.md
  - How To:
    - Logs: how_to/logs.md
  - Classes:
    - ParsedLogs: classes/parser.md
    - Database: classes/db.md
    - EveAnalytics: classes/match_analytics.md
  - Exceptions:
    - Database Errors: exceptions/db.md
    - File Errors: exceptions/file.md
  - Functions:
    - Log Parsing:
      - Combat Logs: funcs/combat_logs.md
      - Matches: funcs/matches.md
    - Diagrams:
      - Flight Diagrams: funcs/pilot_diagrams.md
      - Fleet Diagrams: funcs/fleet_diagrams.md

theme:
  name: material
  favicon: imgs/favicon.ico
  logo: imgs/ea-logo.png
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

repo_url: https://github.com/ender-locke/eve-analytics
repo_name: eve-analytics
copyright: Copyright &copy; 2026 Ender Locke