site_name: eve-analytics

nav:
  - Home: index.md
  - Classes:
    - Parser: classes/parser.md
    - Database: classes/db.md
  - Exceptions:
    - Database Errors: exceptions/db.md
    - File Errors: exceptions/file.md

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/eve-analytics.png
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

repo_url: https://github.com/ender-locke/eve-analytics
repo_name: eve-analytics
copyright: Copyright &copy; 2026 Ender Locke