[build-system]
requires = ["uv-build>=0.11.8"]
build-backend = "uv_build"

[project]
name = "eve-analytics"
version = "0.0.20"
authors = [{ name = "Ender Locke", email = "enderlocke.eve@gmail.com" }]
description = "Analytics package for eve online"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.6",
    "mkdocstrings>=1.0.4",
    "mkdocstrings-python>=2.0.3",
    "pandas>=3.0.1",
    "pillow>=12.1.1",
    "pyyaml>=6.0.3",
    "wget>=3.2",
]
classifiers = [
    # Should be one of:
    # "Development Status :: 3 - Alpha"
    "Development Status :: 4 - Beta",
    # "Development Status :: 5 - Production/Stable"
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    #"Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    #"Programming Language :: Python :: 3.12",
    #"Operating System :: OS Independent",
]
