name: CI/CD Pipeline

on:
  push:
    branches:
      - preprod
      - prod
      - dev

env:
  TWINE_DISABLE_KEYRING: 1

jobs:
  test-build-package:
    name: Test Deploy Package
    #needs: pytest
    runs-on: ubuntu-latest
    environment: preprod
    if: github.ref == 'refs/heads/preprod'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install build tools
        run: pip install build

      - name: Build package
        run: python -m build

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.PYPI_API_TOKEN }}

  build-package:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    environment: prod
    if: github.ref == 'refs/heads/prod'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install build tools
        run: pip install build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  test-mkdocs:
    name: Test Build mkdocs
    environment: preprod
    needs: test-build-package
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/preprod'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocstrings mkdocstrings-python

      - name: Test MkDocs Build
        run: mkdocs build --strict

  deploy-mkdocs:
    name: Deploy mkdocs
    needs: build-package
    environment: prod
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocstrings mkdocstrings-python

      - name: Build the MkDocs site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
